import{S as f,i as d}from"./assets/vendor-9310f15c.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const m="https://pixabay.com/api",y="41864490-ab1aa9c4772cfd6b871252eca";function g(t,o="photo",n="horizontal",l=!0){return fetch(`${m}/?key=${y}&q=${t}&image_type=${o}&orientation=${n}&safesearch=${l}&per_page=18`).then(e=>{if(!e.ok)throw new Error(e.statusText);return e.json()})}let s;const a={loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),searchForm:document.querySelector(".search-form")};a.searchForm.addEventListener("submit",h);function h(t){t.preventDefault();const o=t.currentTarget,n=o.elements.query.value;a.gallery.innerHTML="",S(),g(n).then(p).catch(L).finally(()=>{w(),o.reset()})}function p({hits:t}){if(t.length===0){$();return}const o=t.map(({comments:n,downloads:l,largeImageURL:e,likes:r,webformatURL:i,tags:c,views:u})=>`<li class="gallery-item">
        <a class="gallery-link" href="${e}" target="_blank">
          <img class="gallery-image" src="${i}" alt="${c}">
          <ul class="gallery-item-description">
            <li>Likes: ${r}</li>
            <li>Views: ${u}</li>
            <li>Downloads: ${l}</li>
            <li>Comments: ${n}</li>
          </ul>
        </a>
      </li>`).join("");a.gallery.innerHTML=o,s=new f(".gallery-item a",{captionsData:"alt",captionDelay:250}),s.refresh()}function L(t){alert("Упс, щось пішло не так і ми не знайшли вашого покемона!"),console.error(t)}function $(){d.show({class:"error-svg",icon:"error-svg",theme:"dark",message:"Sorry, there are no images matching your search query. Please try again! Please choose a date in the future",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3})}const b=a.searchForm.querySelector(".form-control");b.addEventListener("focus",()=>{a.gallery.innerHTML=""});function S(){a.loader.style.display="block"}function w(){a.loader.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
