import{S as u,i as m}from"./assets/vendor-9310f15c.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const f="https://pixabay.com/api",d="41864490-ab1aa9c4772cfd6b871252eca",n={searchForm:document.querySelector(".search-form"),loader:document.querySelector(".loader"),imageList:document.querySelector(".gallery")},g=new u(".gallery-item a",{captionsData:"alt",captionDelay:250});n.searchForm.addEventListener("submit",h);function h(r){r.preventDefault();const o=r.currentTarget,i=o.elements.query.value;n.imageList.innerHTML="",b(),y(i).then(p).catch(L).finally(()=>{$(),o.reset()})}function y(r,o="photo",i="horizontal",a=!0){return fetch(`${f}/?key=${d}&q=${r}&image_type=${o}&orientation=${i}&safesearch=${a}&per_page=18`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function p({hits:r}){if(r.length===0){l("Sorry, there are no images matching your search query. Please try again!");return}n.imageList.innerHTML=w(r),g.refresh()}function l(r=""){const o=r||"Sorry, there was an error fetching images.";m.show({iconUrl:"../img/error.svg",theme:"dark",message:o,messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3})}function L(r){n.imageList.innerHTML="",l("Sorry, there is a problem with connection with the server.")}function w(r){return r.map(({comments:o,downloads:i,largeImageURL:a,likes:e,webformatURL:t,tags:s,views:c})=>`<li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${t}" alt="${s}">
          <ul class="gallery-item-description">
            <li>Likes: ${e}</li>
            <li>Views: ${c}</li>
            <li>Downloads: ${i}</li>
            <li>Comments: ${o}</li>
          </ul>
        </a>
      </li>`).join("")}function $(){setTimeout(()=>{n.loader.style.display="none"},500)}function b(){n.loader.style.display!=="block"&&(n.loader.style.display="block")}
//# sourceMappingURL=commonHelpers.js.map
