import{S as u,i as m}from"./assets/vendor-9310f15c.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const f="https://pixabay.com/api",g="41864490-ab1aa9c4772cfd6b871252eca",s={searchForm:document.querySelector(".search-form"),loader:document.querySelector(".loader"),imageList:document.querySelector(".gallery")},d=new u(".gallery-item a",{captionsData:"alt",captionDelay:250});s.searchForm.addEventListener("submit",h);function h(r){r.preventDefault();const o=r.currentTarget,i=o.elements.query.value;s.imageList.innerHTML="",y(i).then(p).catch(L).finally(()=>{w(),o.reset()})}function y(r,o="photo",i="horizontal",n=!0){return fetch(`${f}/?key=${g}&q=${r}&image_type=${o}&orientation=${i}&safesearch=${n}&per_page=18`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function p({hits:r}){if(r.length===0){l("Sorry, there are no images matching your search query. Please try again!");return}s.imageList.innerHTML=$(r),d.refresh()}function l(r=""){const o=r||"Sorry, there was an error fetching images.";m.show({iconUrl:"/img/error.svg",theme:"dark",message:o,messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3})}function L(r){s.imageList.innerHTML="",l("Sorry, there is a problem with connection with the server.")}function $(r){return r.map(({comments:o,downloads:i,largeImageURL:n,likes:e,webformatURL:t,tags:a,views:c})=>`<li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <img class="gallery-image" src="${t}" alt="${a}">
          <ul class="gallery-item-description">
            <li>Likes: ${e}</li>
            <li>Views: ${c}</li>
            <li>Downloads: ${i}</li>
            <li>Comments: ${o}</li>
          </ul>
        </a>
      </li>`).join("")}function w(){setTimeout(()=>{s.loader.style.display="none"},500)}
//# sourceMappingURL=commonHelpers.js.map
